<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Acerca de nosotros' => '',
    'Ayuda' => '',
    'Contacto' => '',
    'Desarrollado por Alonso García' => '',
    'Descripción del error' => '',
    'El proyecto "Venénciame" está enfocado a una tienda online para la venta de vinos españoles de denominación de origen, ofreciéndo un servicio a pequeñas bodegas que desean abrirse en el mercado.' => '',
    'Imagen animada de copa de vino' => '',
    'Ir a la ayuda del sitio web' => '',
    'Ir a la página de contacto' => '',
    'Ir a la página principal' => '',
    'Lea más acerca de nuestra empresa' => '',
    'Mensaje de error' => '',
    'Navegue entre nuestra gran colección de vinos' => '',
    'Nuestros vinos' => '',
    'Perfil del desarrollador en GitHub' => '',
];
